name: Compile & test on push and PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: Compile & Test
        run: make all